using System.Diagnostics;
using System.Text;
using TLScope.Models;
using TLScope.Utilities;
using Serilog;

namespace TLScope.Services;

/// <summary>
/// Service for generating comprehensive LaTeX reports with PDF compilation
/// </summary>
public class LatexReportService
{
    /// <summary>
    /// Generate complete LaTeX report and optionally compile to PDF
    /// </summary>
    public async Task<(bool success, string filePath, bool isPdf)> ExportLatexReport(ReportData data, string baseFilename)
    {
        try
        {
            // Write .dot file separately
            var dotPath = baseFilename + ".dot";
            await File.WriteAllTextAsync(dotPath, data.DotGraphContent);
            Log.Information($"DOT file generated: {dotPath}");

            // Generate LaTeX content (pass dot filename for reference)
            var dotFilename = Path.GetFileName(dotPath);
            var latexContent = GenerateLatexDocument(data, dotFilename);

            // Write .tex file
            var texPath = baseFilename + ".tex";
            await File.WriteAllTextAsync(texPath, latexContent);
            Log.Information($"LaTeX file generated: {texPath}");

            // Check LaTeX availability and attempt compilation
            if (CheckLatexAvailability())
            {
                bool compiled = await CompileToPdf(texPath, baseFilename);

                if (compiled && File.Exists(baseFilename + ".pdf"))
                {
                    Log.Information($"PDF successfully generated: {baseFilename}.pdf");
                    return (true, baseFilename + ".pdf", true);
                }
            }

            // Fallback: return .tex file
            return (true, texPath, false);
        }
        catch (Exception ex)
        {
            Log.Error(ex, "Failed to generate LaTeX report");
            return (false, string.Empty, false);
        }
    }

    /// <summary>
    /// Generate complete LaTeX document
    /// </summary>
    private string GenerateLatexDocument(ReportData data, string dotFilename)
    {
        dotFilename = LatexHelpers.EscapeLatex(dotFilename);
        var sb = new StringBuilder();

        // Document preamble
        sb.AppendLine(GeneratePreamble());

        // Begin document
        sb.AppendLine("\\begin{document}");
        sb.AppendLine();

        // Title page
        sb.AppendLine(GenerateTitlePage(data));

        // Table of contents
        sb.AppendLine("\\tableofcontents");
        sb.AppendLine("\\newpage");
        sb.AppendLine();

        // Report sections
        sb.AppendLine(GenerateExecutiveSummary(data));
        sb.AppendLine(GenerateDeviceInventory(data));
        sb.AppendLine(GenerateConnectionAnalysis(data));
        sb.AppendLine(GenerateNetworkTopology(data));
        sb.AppendLine(GenerateGraphMetrics(data));
        sb.AppendLine(GeneratePeerNetwork(data));
        sb.AppendLine(GenerateTrafficStatistics(data));
        sb.AppendLine(GenerateSecurityConfiguration(data));
        sb.AppendLine(GenerateAppendices(data, dotFilename));

        // End document
        sb.AppendLine("\\end{document}");

        return sb.ToString();
    }

    /// <summary>
    /// Generate LaTeX preamble with packages and styling
    /// </summary>
    private string GeneratePreamble()
    {
        return @"\documentclass[11pt,a4paper]{article}

% Packages
\usepackage[utf8]{inputenc}
\usepackage[margin=1in]{geometry}
\usepackage{graphicx}
\usepackage{tikz}
\usepackage{pgfplots}
\pgfplotsset{compat=1.18}
\usepackage{longtable}
\usepackage{booktabs}
\usepackage{xcolor}
\usepackage{hyperref}
\usepackage{fancyhdr}
\usepackage{lastpage}
\usepackage{listings}
\usepackage{colortbl}

% Custom colors
\definecolor{tlsblue}{RGB}{0,120,215}
\definecolor{tlsgreen}{RGB}{16,124,16}
\definecolor{tlsred}{RGB}{232,17,35}
\definecolor{tlsgray}{RGB}{135,135,135}
\definecolor{activebg}{RGB}{240,255,240}
\definecolor{inactivebg}{RGB}{245,245,245}

% Hyperref setup
\hypersetup{
    colorlinks=true,
    linkcolor=tlsblue,
    filecolor=tlsblue,
    urlcolor=tlsblue,
    citecolor=tlsblue
}

% Header and footer
\pagestyle{fancy}
\fancyhf{}
\fancyhead[L]{TLScope Network Analysis Report}
\fancyhead[R]{\thepage\ of \pageref{LastPage}}
\fancyfoot[C]{Generated by TLScope v1.0.0}

% Title formatting
\title{\textbf{TLScope}\\ Network Security Analysis Report}
\author{TLScope Network Security Visualization Tool}
\date{}
";
    }

    /// <summary>
    /// Generate title page
    /// </summary>
    private string GenerateTitlePage(ReportData data)
    {
        var sb = new StringBuilder();

        sb.AppendLine("\\maketitle");
        sb.AppendLine("\\thispagestyle{empty}");
        sb.AppendLine();

        // Report metadata box
        sb.AppendLine("\\begin{center}");
        sb.AppendLine("\\large");
        sb.AppendLine("\\begin{tabular}{rl}");
        sb.AppendLine("\\toprule");
        sb.AppendLine("\\multicolumn{2}{c}{\\textbf{Report Information}} \\\\");
        sb.AppendLine("\\midrule");
        sb.AppendLine($"Generated: & {LatexHelpers.EscapeLatex(LatexHelpers.FormatTimestamp(data.ReportGeneratedAt))} \\\\");
        sb.AppendLine($"User: & {LatexHelpers.EscapeLatex(data.CurrentUser?.Username ?? "Unknown")} \\\\");
        sb.AppendLine($"Interface: & {LatexHelpers.EscapeLatex(data.NetworkInterface)} \\\\");
        sb.AppendLine($"Session Duration: & {LatexHelpers.EscapeLatex(LatexHelpers.FormatDuration(data.SessionDuration))} \\\\");
        sb.AppendLine("\\bottomrule");
        sb.AppendLine("\\end{tabular}");
        sb.AppendLine("\\end{center}");
        sb.AppendLine();

        // Key statistics box
        sb.AppendLine("\\vspace{1cm}");
        sb.AppendLine("\\begin{center}");
        sb.AppendLine("\\large");
        sb.AppendLine("\\begin{tabular}{rl}");
        sb.AppendLine("\\toprule");
        sb.AppendLine("\\multicolumn{2}{c}{\\textbf{Network Summary}} \\\\");
        sb.AppendLine("\\midrule");
        sb.AppendLine($"Total Devices: & {data.TotalDevices} \\\\");
        sb.AppendLine($"Active Devices: & \\textcolor{{tlsgreen}}{{{data.ActiveDevices}}} \\\\");
        sb.AppendLine($"Total Connections: & {data.TotalConnections} \\\\");
        sb.AppendLine($"Total Traffic: & {LatexHelpers.EscapeLatex(LatexHelpers.FormatBytes(data.TotalBytes))} \\\\");
        sb.AppendLine($"Network Resilience (Vertex Cut): & {data.VertexCut} \\\\");
        sb.AppendLine("\\bottomrule");
        sb.AppendLine("\\end{tabular}");
        sb.AppendLine("\\end{center}");
        sb.AppendLine();

        sb.AppendLine("\\newpage");
        return sb.ToString();
    }

    /// <summary>
    /// Generate executive summary section
    /// </summary>
    private string GenerateExecutiveSummary(ReportData data)
    {
        var sb = new StringBuilder();

        sb.AppendLine("\\section{Executive Summary}");
        sb.AppendLine();

        sb.AppendLine("This report provides a comprehensive analysis of network activity captured by TLScope.");
        sb.AppendLine($"During the monitoring period of {LatexHelpers.EscapeLatex(LatexHelpers.FormatDuration(data.SessionDuration))}, ");
        sb.AppendLine($"the system discovered {data.TotalDevices} network devices and observed {data.TotalConnections} connections, ");
        sb.AppendLine($"transferring a total of {LatexHelpers.EscapeLatex(LatexHelpers.FormatBytes(data.TotalBytes))} ({data.TotalPackets:N0} packets).");
        sb.AppendLine();

        // Key highlights
        sb.AppendLine("\\subsection*{Key Highlights}");
        sb.AppendLine("\\begin{itemize}");
        sb.AppendLine($"\\item {data.ActiveDevices} devices currently active ({(data.TotalDevices > 0 ? (data.ActiveDevices * 100.0 / data.TotalDevices):0):F1}\\% of total)");
        sb.AppendLine($"\\item {data.TLSPeersDiscovered} TLScope peers discovered, {data.ConnectedPeers} currently connected");
        sb.AppendLine($"\\item Network vertex cut of {data.VertexCut} indicates {(data.VertexCut > 2 ? "good" : "limited")} network resilience");
        sb.AppendLine($"\\item Average of {data.AverageConnectionsPerDevice:F2} connections per device");

        if (data.MostConnectedDevice != null)
        {
            var deviceName = LatexHelpers.EscapeLatex(data.MostConnectedDevice.Hostname ?? data.MostConnectedDevice.IPAddress);
            sb.AppendLine($"\\item Most connected device: {deviceName} with {data.MostConnectedCount} connections");
        }

        sb.AppendLine("\\end{itemize}");
        sb.AppendLine();
        sb.AppendLine("\\newpage");

        return sb.ToString();
    }

    /// <summary>
    /// Generate device inventory table
    /// </summary>
    private string GenerateDeviceInventory(ReportData data)
    {
        var sb = new StringBuilder();

        sb.AppendLine("\\section{Device Inventory}");
        sb.AppendLine();
        sb.AppendLine($"Total devices discovered: {data.TotalDevices} ({data.ActiveDevices} active, {data.InactiveDevices} inactive)");
        sb.AppendLine();

        // Ultra-compact table formatting
        sb.AppendLine("{\\footnotesize");  // Footnote-sized font (smaller than \small)
        sb.AppendLine("\\setlength{\\tabcolsep}{4pt}");  // Reduce column padding slightly

        // Device table - auto-sized columns
        sb.AppendLine("\\begin{longtable}{lllllrrl}");
        sb.AppendLine("\\toprule");
        sb.AppendLine("\\textbf{Device} & \\textbf{IP} & \\textbf{MAC} & \\textbf{Vendor} & \\textbf{St.} & \\textbf{Pkts} & \\textbf{Bytes} & \\textbf{Seen} \\\\");
        sb.AppendLine("\\midrule");
        sb.AppendLine("\\endfirsthead");
        sb.AppendLine("\\multicolumn{8}{c}{{\\tablename\\ \\thetable{} -- continued}} \\\\");
        sb.AppendLine("\\toprule");
        sb.AppendLine("\\textbf{Device} & \\textbf{IP} & \\textbf{MAC} & \\textbf{Vendor} & \\textbf{St.} & \\textbf{Pkts} & \\textbf{Bytes} & \\textbf{Seen} \\\\");
        sb.AppendLine("\\midrule");
        sb.AppendLine("\\endhead");
        sb.AppendLine("\\midrule");
        sb.AppendLine("\\multicolumn{8}{r}{{Continued}} \\\\");
        sb.AppendLine("\\endfoot");
        sb.AppendLine("\\bottomrule");
        sb.AppendLine("\\endlastfoot");

        foreach (var device in data.Devices.OrderByDescending(d => d.LastSeen).Take(150))
        {
            // Compact but readable names
            var deviceName = LatexHelpers.Truncate(device.Hostname ?? device.DeviceName ?? device.IPAddress, 20);
            var ip = device.IPAddress;

            // Compact MAC: show last 8 chars only (e.g., "...34:56:78")
            var mac = device.MACAddress;

            var vendor = LatexHelpers.Truncate(device.Vendor ?? "Unknown", 15);

            // Ultra-compact status: A/I symbols with color
            var status = device.IsActive ? "\\textcolor{tlsgreen}{A}" : "\\textcolor{tlsgray}{I}";

            // Compact numbers
            var packets = device.PacketCount >= 1000
                ? $"{device.PacketCount / 1000.0:F1}k"
                : device.PacketCount.ToString();

            var bytes = LatexHelpers.FormatBytes(device.BytesTransferred);

            // Relative time format for compactness (e.g., "2m", "5h", "3d")
            var lastSeen = LatexHelpers.FormatRelativeTime(device.LastSeen);

            var rowColor = device.IsActive ? "\\rowcolor{activebg} " : "";
            sb.AppendLine($"{rowColor}{LatexHelpers.EscapeLatex(deviceName)} & {LatexHelpers.EscapeLatex(ip)} & {LatexHelpers.EscapeLatex(mac)} & {LatexHelpers.EscapeLatex(vendor)} & {status} & {packets} & {LatexHelpers.EscapeLatex(bytes)} & {LatexHelpers.EscapeLatex(lastSeen)} \\\\");
        }

        sb.AppendLine("\\end{longtable}");
        sb.AppendLine("}");  // End small font block
        sb.AppendLine("\\newpage");

        return sb.ToString();
    }

    /// <summary>
    /// Generate connection analysis section
    /// </summary>
    private string GenerateConnectionAnalysis(ReportData data)
    {
        var sb = new StringBuilder();

        sb.AppendLine("\\section{Connection Analysis}");
        sb.AppendLine();

        // Connection summary
        sb.AppendLine("\\subsection{Connection Summary}");
        sb.AppendLine("\\begin{tabular}{lr}");
        sb.AppendLine("\\toprule");
        sb.AppendLine($"Total Connections: & {data.TotalConnections} \\\\");
        sb.AppendLine($"Active Connections: & \\textcolor{{tlsgreen}}{{{data.ActiveConnections}}} \\\\");
        sb.AppendLine($"Avg Connections/Device: & {data.AverageConnectionsPerDevice:F2} \\\\");
        sb.AppendLine("\\bottomrule");
        sb.AppendLine("\\end{tabular}");
        sb.AppendLine();

        // Protocol distribution
        if (data.ProtocolDistribution.Any())
        {
            sb.AppendLine("\\subsection{Protocol Distribution}");
            sb.AppendLine("\\begin{tabular}{lr}");
            sb.AppendLine("\\toprule");
            sb.AppendLine("\\textbf{Protocol} & \\textbf{Count} \\\\");
            sb.AppendLine("\\midrule");

            foreach (var kvp in data.ProtocolDistribution.OrderByDescending(x => x.Value))
            {
                sb.AppendLine($"{LatexHelpers.EscapeLatex(kvp.Key)} & {kvp.Value} \\\\");
            }

            sb.AppendLine("\\bottomrule");
            sb.AppendLine("\\end{tabular}");
            sb.AppendLine();
        }

        // Top connections
        sb.AppendLine("\\subsection{Top Connections by Traffic}");
        sb.AppendLine("\\begin{longtable}{llllrr}");
        sb.AppendLine("\\toprule");
        sb.AppendLine("\\textbf{Source} & \\textbf{Destination} & \\textbf{Protocol} & \\textbf{Port} & \\textbf{Packets} & \\textbf{Bytes} \\\\");
        sb.AppendLine("\\midrule");

        foreach (var conn in data.Connections.OrderByDescending(c => c.BytesTransferred).Take(20))
        {
            var src = LatexHelpers.Truncate(conn.SourceDevice.Hostname ?? conn.SourceDevice.IPAddress, 15);
            var dst = LatexHelpers.Truncate(conn.DestinationDevice.Hostname ?? conn.DestinationDevice.IPAddress, 15);
            var protocol = conn.Protocol ?? "Unknown";
            var port = conn.DestinationPort?.ToString() ?? "-";
            var packets = conn.PacketCount.ToString("N0");
            var bytes = LatexHelpers.FormatBytes(conn.BytesTransferred);

            sb.AppendLine($"{LatexHelpers.EscapeLatex(src)} & {LatexHelpers.EscapeLatex(dst)} & {LatexHelpers.EscapeLatex(protocol)} & {port} & {packets} & {LatexHelpers.EscapeLatex(bytes)} \\\\");
        }

        sb.AppendLine("\\bottomrule");
        sb.AppendLine("\\end{longtable}");
        sb.AppendLine();

        return sb.ToString();
    }

    /// <summary>
    /// Generate network topology section (placeholder for TikZ graph)
    /// </summary>
    private string GenerateNetworkTopology(ReportData data)
    {
        var sb = new StringBuilder();

        sb.AppendLine("\\section{Network Topology}");
        sb.AppendLine();
        sb.AppendLine("\\subsection{Topology Visualization}");
        sb.AppendLine();
        sb.AppendLine("% TODO: Implement TikZ network graph visualization");
        sb.AppendLine("% Convert force-directed layout coordinates to TikZ node positions");
        sb.AppendLine("The network topology graph will be rendered here using TikZ.");
        sb.AppendLine();

        return sb.ToString();
    }

    /// <summary>
    /// Generate graph metrics section
    /// </summary>
    private string GenerateGraphMetrics(ReportData data)
    {
        var sb = new StringBuilder();

        sb.AppendLine("\\section{Graph Metrics \\& Analysis}");
        sb.AppendLine();

        sb.AppendLine("\\begin{tabular}{lr}");
        sb.AppendLine("\\toprule");
        sb.AppendLine($"Vertex Count (Devices): & {data.TotalDevices} \\\\");
        sb.AppendLine($"Edge Count (Connections): & {data.TotalConnections} \\\\");
        sb.AppendLine($"Average Degree: & {data.AverageConnectionsPerDevice:F2} \\\\");
        sb.AppendLine($"Vertex Cut (Min): & {data.VertexCut} \\\\");

        if (data.MostConnectedDevice != null)
        {
            var deviceName = LatexHelpers.EscapeLatex(data.MostConnectedDevice.Hostname ?? data.MostConnectedDevice.IPAddress);
            sb.AppendLine($"Most Connected Node: & {deviceName} ({data.MostConnectedCount} connections) \\\\");
        }

        sb.AppendLine("\\bottomrule");
        sb.AppendLine("\\end{tabular}");
        sb.AppendLine();

        sb.AppendLine("\\subsection*{Vertex Cut Explanation}");
        sb.AppendLine("The vertex cut (vertex connectivity) represents the minimum number of nodes that must be removed ");
        sb.AppendLine("to disconnect the network. A higher vertex cut indicates better network resilience and redundancy. ");
        sb.AppendLine($"This network has a vertex cut of {data.VertexCut}, meaning at least {data.VertexCut} ");
        sb.AppendLine("device(s) must fail simultaneously to partition the network.");
        sb.AppendLine();

        return sb.ToString();
    }

    /// <summary>
    /// Generate TLS peer network section
    /// </summary>
    private string GeneratePeerNetwork(ReportData data)
    {
        var sb = new StringBuilder();

        sb.AppendLine("\\section{TLScope Peer Network}");
        sb.AppendLine();

        if (data.Peers.Count == 0)
        {
            sb.AppendLine("No TLScope peers discovered on the network.");
            sb.AppendLine();
            return sb.ToString();
        }

        sb.AppendLine($"Total peers discovered: {data.TLSPeersDiscovered} ({data.ConnectedPeers} connected)");
        sb.AppendLine();

        sb.AppendLine("\\begin{longtable}{llllll}");
        sb.AppendLine("\\toprule");
        sb.AppendLine("\\textbf{Username} & \\textbf{IP:Port} & \\textbf{Status} & \\textbf{Verified} & \\textbf{Devices} & \\textbf{Last Connected} \\\\");
        sb.AppendLine("\\midrule");

        foreach (var peer in data.Peers.OrderByDescending(p => p.IsConnected).ThenByDescending(p => p.LastConnected))
        {
            var username = LatexHelpers.Truncate(peer.Username ?? "Unknown", 15);
            var address = $"{peer.IPAddress}:{peer.Port}";
            var status = peer.IsConnected ? "\\textcolor{tlsgreen}{Connected}" : "Disconnected";
            var verified = peer.IsVerified ? "\\textcolor{tlsgreen}{Yes}" : "No";
            var devices = peer.DeviceCount.ToString();
            var lastConnected = LatexHelpers.FormatTimestamp(peer.LastConnected);

            sb.AppendLine($"{LatexHelpers.EscapeLatex(username)} & {LatexHelpers.EscapeLatex(address)} & {status} & {verified} & {devices} & {LatexHelpers.EscapeLatex(lastConnected)} \\\\");
        }

        sb.AppendLine("\\bottomrule");
        sb.AppendLine("\\end{longtable}");
        sb.AppendLine();

        return sb.ToString();
    }

    /// <summary>
    /// Generate traffic statistics section
    /// </summary>
    private string GenerateTrafficStatistics(ReportData data)
    {
        var sb = new StringBuilder();

        sb.AppendLine("\\section{Traffic Statistics}");
        sb.AppendLine();

        sb.AppendLine("\\begin{tabular}{lr}");
        sb.AppendLine("\\toprule");
        sb.AppendLine($"Total Packets: & {data.TotalPackets:N0} \\\\");
        sb.AppendLine($"Total Bytes: & {LatexHelpers.EscapeLatex(LatexHelpers.FormatBytes(data.TotalBytes))} \\\\");
        sb.AppendLine($"Active Connections: & {data.ActiveConnections} \\\\");
        sb.AppendLine("\\bottomrule");
        sb.AppendLine("\\end{tabular}");
        sb.AppendLine();

        return sb.ToString();
    }

    /// <summary>
    /// Generate security configuration section
    /// </summary>
    private string GenerateSecurityConfiguration(ReportData data)
    {
        var sb = new StringBuilder();

        sb.AppendLine("\\section{Security \\& Configuration}");
        sb.AppendLine();

        if (data.FilterConfig != null)
        {
            sb.AppendLine("\\subsection{Filter Configuration}");
            sb.AppendLine("\\begin{tabular}{ll}");
            sb.AppendLine("\\toprule");
            sb.AppendLine($"Filter Loopback: & {(data.FilterConfig.FilterLoopback ? "Enabled" : "Disabled")} \\\\");
            sb.AppendLine($"Filter Broadcast: & {(data.FilterConfig.FilterBroadcast ? "Enabled" : "Disabled")} \\\\");
            sb.AppendLine($"Filter Multicast: & {(data.FilterConfig.FilterMulticast ? "Enabled" : "Disabled")} \\\\");
            sb.AppendLine($"Filter Link-Local: & {(data.FilterConfig.FilterLinkLocal ? "Enabled" : "Disabled")} \\\\");
            sb.AppendLine($"Block Duplicates: & {(data.FilterConfig.BlockDuplicateIPs ? "Enabled" : "Disabled")} \\\\");
            sb.AppendLine($"Total Filtered: & {data.FilterConfig.TotalFiltered:N0} \\\\");
            sb.AppendLine($"Duplicates Blocked: & {data.FilterConfig.DuplicatesBlocked:N0} \\\\");
            sb.AppendLine("\\bottomrule");
            sb.AppendLine("\\end{tabular}");
            sb.AppendLine();
        }

        if (data.ExcludedIPs.Any() || data.ExcludedHostnames.Any() || data.ExcludedMACs.Any())
        {
            sb.AppendLine("\\subsection{Exclusions}");
            if (data.ExcludedIPs.Any())
            {
                sb.AppendLine($"\\textbf{{Excluded IPs:}} {string.Join(", ", data.ExcludedIPs.Select(LatexHelpers.EscapeLatex))}");
                sb.AppendLine();
            }
            if (data.ExcludedHostnames.Any())
            {
                sb.AppendLine($"\\textbf{{Excluded Hostnames:}} {string.Join(", ", data.ExcludedHostnames.Select(LatexHelpers.EscapeLatex))}");
                sb.AppendLine();
            }
            if (data.ExcludedMACs.Any())
            {
                sb.AppendLine($"\\textbf{{Excluded MACs:}} {string.Join(", ", data.ExcludedMACs.Select(LatexHelpers.EscapeLatex))}");
                sb.AppendLine();
            }
        }

        return sb.ToString();
    }

    /// <summary>
    /// Generate appendices section
    /// </summary>
    private string GenerateAppendices(ReportData data, string dotFilename)
    {
        var sb = new StringBuilder();

        sb.AppendLine("\\appendix");
        sb.AppendLine();

        // Appendix A: DOT Graph Export
        sb.AppendLine("\\section{DOT Graph Export}");
        sb.AppendLine("The following is the Graphviz DOT format export of the network graph, ");
        sb.AppendLine($"which can be imported into graph visualization tools. The complete DOT file is ");
        sb.AppendLine($"available as \\texttt{{{dotFilename}}}.");
        sb.AppendLine();
        sb.AppendLine("\\lstinputlisting[");
        sb.AppendLine("    breaklines=true,");
        sb.AppendLine("    basicstyle=\\small\\ttfamily,");
        sb.AppendLine("    frame=single,");
        sb.AppendLine("    numbers=left,");
        sb.AppendLine("    numberstyle=\\tiny\\color{gray},");
        sb.AppendLine($"    caption={{Network Graph DOT Export: {dotFilename}}}");
        sb.AppendLine($"]{{{dotFilename}}}");
        sb.AppendLine();

        return sb.ToString();
    }

    /// <summary>
    /// Check if LaTeX is available on the system
    /// </summary>
    private bool CheckLatexAvailability()
    {
        try
        {
            var psi = new ProcessStartInfo
            {
                FileName = "pdflatex",
                Arguments = "--version",
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                CreateNoWindow = true
            };

            using var process = Process.Start(psi);
            return process != null && process.WaitForExit(2000);
        }
        catch
        {
            return false;
        }
    }

    /// <summary>
    /// Compile LaTeX file to PDF
    /// </summary>
    private async Task<bool> CompileToPdf(string texPath, string baseFilename)
    {
        try
        {
            var directory = Path.GetDirectoryName(texPath) ?? ".";

            // Run pdflatex twice (for references)
            for (int i = 0; i < 2; i++)
            {
                var psi = new ProcessStartInfo
                {
                    FileName = "pdflatex",
                    Arguments = $"-interaction=nonstopmode -output-directory=\"{directory}\" \"{texPath}\"",
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    UseShellExecute = false,
                    CreateNoWindow = true,
                    WorkingDirectory = directory
                };

                using var process = Process.Start(psi);
                if (process == null)
                    return false;

                await process.WaitForExitAsync();

                if (process.ExitCode != 0)
                {
                    var error = await process.StandardError.ReadToEndAsync();
                    Log.Warning($"pdflatex run {i + 1} failed: {error}");
                    return false;
                }
            }

            // Clean up auxiliary files
            var auxExtensions = new[] { ".aux", ".log", ".out", ".toc" };
            foreach (var ext in auxExtensions)
            {
                var auxFile = baseFilename + ext;
                if (File.Exists(auxFile))
                {
                    try { File.Delete(auxFile); } catch { }
                }
            }

            return File.Exists(baseFilename + ".pdf");
        }
        catch (Exception ex)
        {
            Log.Error(ex, "PDF compilation failed");
            return false;
        }
    }
}
