// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TLScope.Data;

#nullable disable

namespace TLScope.src.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251111061748_NormalizeDevicePorts")]
    partial class NormalizeDevicePorts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("TLScope.Models.Connection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AverageTTL")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesTransferred")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DestinationDeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DestinationPort")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTLSPeerConnection")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxTTL")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinTTL")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PacketCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PacketCountForTTL")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceDeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourcePort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DestinationDeviceId");

                    b.HasIndex("LastSeen");

                    b.HasIndex("Type");

                    b.HasIndex("SourceDeviceId", "DestinationDeviceId", "Protocol");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("TLScope.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesTransferred")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("GatewayRole")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HopCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hostname")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefaultGateway")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGateway")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTLScopePeer")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("MACAddress")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenPorts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("PacketCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TLSPeerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Vendor")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IPAddress");

                    b.HasIndex("IsGateway");

                    b.HasIndex("IsTLScopePeer");

                    b.HasIndex("LastSeen");

                    b.HasIndex("MACAddress")
                        .IsUnique();

                    b.HasIndex("TLSPeerId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("TLScope.Models.DevicePort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Port");

                    b.HasIndex("DeviceId", "Port", "Protocol")
                        .IsUnique();

                    b.ToTable("DevicePorts");
                });

            modelBuilder.Entity("TLScope.Models.TLSPeer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CombinedRandomartAvatar")
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastConnected")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastVerified")
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SSHPublicKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IPAddress");

                    b.HasIndex("Username");

                    b.ToTable("TLSPeers");
                });

            modelBuilder.Entity("TLScope.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomAvatarLinesStorage")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SSHPrivateKeyPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("SSHPublicKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TLScope.Models.Connection", b =>
                {
                    b.HasOne("TLScope.Models.Device", "DestinationDevice")
                        .WithMany()
                        .HasForeignKey("DestinationDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TLScope.Models.Device", "SourceDevice")
                        .WithMany()
                        .HasForeignKey("SourceDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DestinationDevice");

                    b.Navigation("SourceDevice");
                });

            modelBuilder.Entity("TLScope.Models.Device", b =>
                {
                    b.HasOne("TLScope.Models.TLSPeer", "TLSPeer")
                        .WithMany()
                        .HasForeignKey("TLSPeerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TLSPeer");
                });

            modelBuilder.Entity("TLScope.Models.DevicePort", b =>
                {
                    b.HasOne("TLScope.Models.Device", "Device")
                        .WithMany("Ports")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("TLScope.Models.Device", b =>
                {
                    b.Navigation("Ports");
                });
#pragma warning restore 612, 618
        }
    }
}
